var a = document.createElement("div")
var b = document.createTextNode("Login Page")
var c = document.createElement("input")
c.setAttribute("type", "text")
var d = document.createElement("button")
var e = document.createTextNode("Click")
d.appendChild(e)
a.appendChild(b)
a.appendChild(c)
a.appendChild(d)
document.body.appendChild(a)